### ISSUE TITLE
Sorry...

### ISSUE THREAD

**Issue by jonathan-richer** [shiffman/IMNY-UT-1-Code#1]
I just wanted to know if it was:
1. For anybody
2. Free

**Comment by nishimi-ya** [comment]
This should be Open source and Daniel would be review the code? probably

**Comment by shiffman** [comment]
I am working on an online course as part of my work for NYU. While the course itself is limited to NYU students all of the video content I produce would be available on my YouTube channel and anyone choosing to join the patreon can ask questions and get feedback on their code. Hope this clarifies a bit!

**Comment by nishimi-ya** [comment]
Thanx for the Clarification :+1:

**Comment by jonathan-richer** [comment]
Ok thank you very much!
